version: "2"
services:
  poller:
    build: .
    environment:
      - DB_CONNECTION_STRING=DATABASE=sqlserver://sa:yourStrong(!)Password@db?database=gegdb&connection+timeout=30
    networks:
      - poller-network
  db:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    networks:
      - poller-network
networks:
  poller-network:
    driver: bridge

